name: wirless_wifi
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
analyzer:
  enable-experiment:
    - non-nullable

environment:
  # sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  flutter_native_splash: ^2.1.6
  http: ^0.13.3
  timelines: ^0.1.0
  awesome_dialog: ^2.0.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_staggered_animations: ^1.0.0
  flutter_spinkit: ^5.0.0
  provider: ^6.0.3
  connectivity: ^3.0.3
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.0-nullsafety.1
  file_picker: ^4.6.1
  random_string: ^2.2.0-nullsafety
  flutter_typeahead: ^4.0.0
  geocoding: ^2.0.0
  geolocator: ^8.2.1
  convex_bottom_bar: ^3.0.0-nullsafety.1
  flip_card: ^0.6.0
  feature_discovery: ^0.14.0
  flutter_colorpicker: ^1.0.2
  lottie: ^1.0.1
  badges: ^2.0.0-nullsafety.1
  fluttertoast: ^8.0.7
  cached_network_image: ^3.0.0
  animated_theme_switcher: ^2.0.1-nullsafety.0
  #package animation
  animations: ^2.0.1
  palette_generator: ^0.3.0
  path_provider: ^2.0.2
  #DEVICE INFO
  device_apps: ^2.1.1
  package_info_plus: ^1.3.0
  network_info_plus: ^2.1.3
  wifi_iot: ^0.3.0-nullsafety.0

  
  #wifi_iot: ^0.3.8
#  network_info_plus: ^2.0.2
  device_info_plus: ^3.1.0 #this is for android and ios and web and windows and linux and mac
  battery_plus: ^2.0.1 #this is for android and ios and web and windows and linux and mac
  sensors_plus: ^1.2.1 #this is for android and ios and web and mac
  share_plus: ^4.0.8 #this is for android and ios and web and windows and linux and mac
#   هذ  التي تعمل علا طلب البيانات بشكل تجزيئي مهمه جدا
  infinite_scroll_pagination: ^3.1.0


  snapping_sheet: ^3.1.0

  #مكتبات ليست مهمة للغايه
  fab_circular_menu: ^1.0.2
  expandable_bottom_bar: ^2.0.2
  flutter_utils_project: ^1.1.1
  #Responsive ui
  sizer: ^2.0.15
  
  
  #this is for Security Http
  # http_certificate_pinning: 2.0.3

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/wifi-icon.png
  android: true
  ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
#dependency_overrides:
#  platform: ^3.1.0


  flutter_launcher_icons: ^0.9.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/wifi-icon.png"


flutter:

  uses-material-design: true




  assets:
    - assets/
    - assets/process_timeline/
    - assets/home_images/
    - assets/images/
    - assets/icons/
    - assets/card/
    - assets/data/
    - assets/lottie/
    - assets/networks/
    - assets/icons8-debit-card.gif

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
          style: italic
          weight: 700
 

